name: Docs

on:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: Debug with tmate
        required: false
        default: false

jobs:
  docs:
    runs-on: ubuntu-latest

    name: Docs

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Fetch all tags and branches
        run: git fetch --prune --unshallow

      - name: Create ArangoDB Docker container
        run: docker create --name adb -p 8529:8529 -e ARANGO_ROOT_PASSWORD= arangodb/arangodb

      - name: Start ArangoDB Docker container
        run: docker start adb

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Debug with tmate
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}

      - name: Install dependencies
        run: pip install .[dev]

      - name: Run Sphinx doctest
        run: python -m sphinx -b doctest docs docs/_build

      - name: Generate Sphinx HTML
        run: python -m sphinx -b html -W docs docs/_build
